insert into disquera values (726, 'Independiente');
insert into disquera values (423, 'EMI Music');
insert into disquera values (872, 'Sony Music');
insert into disquera values (567, 'Universal Music Group');
insert into disquera values (955, 'Epic Records');
insert into disquera values (233, 'Warner Music');

insert into genero_musical(234,'Pop Soul');
insert into genero_musical(456,'Cumbia');
insert into genero_musical(789,'Reggae');
insert into genero_musical(112,'Acid Jazz');
insert into genero_musical(134,'Pop');
insert into genero_musical(453,'Hip hop');
insert into genero_musical(933, 'Reggaeton');
insert into genero_musical(587, 'Salsa');
insert into genero_musical(601, 'Ska');
insert into genero_musical(354, 'Indie Rock');

---------------------------------------------------------------------------------------------------
--MODIFICAR idCanciones


insert into artista (1000, 'Adan Cruz', 'Ciudad de México ,México', 453, 872);
	insert into album (1001,'Eso es','2016',1000);
			insert into canciones values(01,'Eso es','3.40','4');
			insert into canciones values(02,'Interludio','2.40','4');
			insert into canciones values(03,'Astronauta de tus Lunares','2.37','5');
			insert into canciones values(04,'Caile a mi Hood','4.35','3');
			insert into canciones values(05,'Hay algo que','2.49','3');
			insert into canciones values(06,'Hey yo','2.46','4');
			insert into canciones values(07,'Mi Corte','4.12','3');
			insert into canciones values(08,'M.O.E.','3.56','3');
			insert into canciones values(09,'No Doubt','3.58','3');
			insert into canciones values(10,'Rólalo y Enciende','5.07','3');
			insert into canciones values(11,'Una Peta en el Barrio','3.10','4');
			insert into canciones values(12,'Welcome to México','4.28','4');
			insert into canciones values(13,'Volare','5.45','4');
  insert into album (1002,'Quiérelo','2015',1000);
			insert into canciones values(01,'Mirame','5.00','4');
			insert into canciones values(02,'We Made a Plan','4.35','5');
			insert into canciones values(03,'Acá en el Norte','3.25','5');
			insert into canciones values(04,'Se llama Adan','3.16','4');
			insert into canciones values(05,'Mobster','3.52','3');
			insert into canciones values(06,'Ándale Nena','3.54','4');
			insert into canciones values(07,'Me Fumo Dos','2.56','3');
			insert into canciones values(08,'Skit','3.46','3');
			insert into canciones values(09,'Roystonea','3.40','4');
			insert into canciones values(10,'Charla Pendiente','4.31','3');
			insert into canciones values(11,'Dale Suave','4.34','4');
			insert into canciones values(12,'Vivir Como Rey','3.54','4');
			insert into canciones values(13,'Quítate Wey','4.08','5');
			insert into canciones values(14,'Quierelo','5.01','4');
			insert into canciones values(15,'Llamale Cera','4.43','5');
			insert into canciones values(16,'Ángeles y Gargolas','3.36','5');
			insert into canciones values(17,'Más Dinero','4.17','3');
			insert into canciones values(18,'Me la Llevo Perron','3.38','3');
			insert into canciones values(19,'They´re Laughing','5.22','4');
			insert into canciones values(20,'Sin Preocupación','6.32','3');
			insert into canciones values(21,'Hacemos Billetes','3.08','3');
			insert into canciones values(22,'Por los que Queremos','3.35','5');

insert into artista (2000, 'Mario Bautista', 'Ciudad de México ,México', 134, 567);
	insert into album (2001,'Aquí Estoy','2016',2000);
			insert into canciones values(01,'Sin Tu Amor','3.52','5');
			insert into canciones values(02,'Te Dedico Esta Canción','3.55','5');
			insert into canciones values(03,'Tu y yo','3.35','5');
			insert into canciones values(04,'LLorar','3.23','3');
			insert into canciones values(05,'Aqui Estoy','3.54','4');
			insert into canciones values(06,'Salvame','3.39','4');
			insert into canciones values(07,'Si Me Das Tu Corazón','3.17','3');
			insert into canciones values(08,'Yo Por Tu Amor','3.37','4');
			insert into canciones values(09,'Siempre Juntos','3.46','4');
			insert into canciones values(10,'Ven a Bailar','3.05','5');
			insert into canciones values(11,'Un Mundo Nuevo','3.17','4');

insert into artista (3000, 'Fun', 'Nueva Jersey', 354, 726);
	insert into album (3001,'Some Nights','2012',3000);
			insert into canciones values(01,'Some Nights','4.37','5');
			insert into canciones values(02,'We Are Young','4.11','5');
			insert into canciones values(03,'Carry On','4.38','5');
			insert into canciones values(04,'It Gets Better','3.36','4');
			insert into canciones values(05,'Why Am I the One','4.47','3');
			insert into canciones values(06,'All Alone','3.04','4');
			insert into canciones values(07,'All Alright','3.58','4');
			insert into canciones values(08,'One Foot','3.32','4');
			insert into canciones values(09,'Stars','6.53','3');
			insert into canciones values(10,'Out On the Twon','4.21','4');
	insert into album (3002,'Gran Romantic','2015',3000)
			insert into canciones values(01,'Grand Romantic','0.43','5');
			insert into canciones values(02,'AhHa','4.24','5');
			insert into canciones values(03,'Nothing Without Love','3.57','5');
			insert into canciones values(04,'Take It Back','4.24','3');
			insert into canciones values(05,'You Light My Fire','3.14','4');
			insert into canciones values(06,'What This World Is Coming To','4.03','4');
			insert into canciones values(07,'Great Big Storm','4.01','3');
			insert into canciones values(08,'Moment','4.13','4');
			insert into canciones values(09,'It Only Gets Much Worse','4.18','4');
			insert into canciones values(10,'Grand Light','3.36','5');
			insert into canciones values(11,'Harsh Light','4.51','4');
			insert into canciones values(12,'Brightside','4.35','4');

insert into artista (4000, 'J Balvin', 'Colombia,Medellín', 933, 872);
	insert into album (4001,'Energía','2015',4000)
			insert into canciones values(01,'Veneno','2.30','4');
			insert into canciones values(02,'Malvada','2.59','5');
			insert into canciones values(03,'Safari','3.26','5');
			insert into canciones values(04,'Bobo','3.29','5');
			insert into canciones values(05,'Sigo Extrañandote','3.21','4');
			insert into canciones values(06,'Primera Cita','2.54','4');
			insert into canciones values(07,'Pierde los Modales','3.21','3');
			insert into canciones values(08,'Por un Día','3.32','4');
			insert into canciones values(09,'Acércate','3.13','4');
			insert into canciones values(10,'Snapchat','3.40','5');
			insert into canciones values(11,'Hola','3.16','5');
			insert into canciones values(12,'Ginza','2.51','5');
	insert into album (4002,'La Familia','2013',4000)
			insert into canciones values(01,'Sola','3.47','4');
			insert into canciones values(02,'La Venganza','3.26','5');
			insert into canciones values(03,'Déjate Llevar','3.11','5');
			insert into canciones values(04,'Mil Fantasías','3.41','5');
			insert into canciones values(05,'6 AM','4.03','4');
			insert into canciones values(06,'Lose Control','4.54','4');
			insert into canciones values(07,'Eras Así','3.47','3');
			insert into canciones values(08,'What a Creation','2.28','4');
			insert into canciones values(09,'Desnúdate','3.43','4');
			insert into canciones values(10,'Imaginándote','3.36','5');
			insert into canciones values(11,'Bajo la Luna','3.35','5');
			insert into canciones values(12,'Live in Stereo','3.30','5');
			insert into canciones values(13,'Porque Tu','2.55','5');
			insert into canciones values(14,'Tranquila','3.20','5');
			insert into canciones values(15,'Yo Te lo Dije','3.40','5');

insert into artista (5000, 'León Larregui', 'México, Cuernavaca', 354, 955);
	insert into album (5001,'Voluma','2015',5000);
			insert into canciones values(01,'Locos','3.47','5');
			insert into canciones values(02,'Zombies','3.26','5');
			insert into canciones values(03,'Mar','3.11','5');
			insert into canciones values(04,'Tremantra','3.41','3');
			insert into canciones values(05,'Tiraste A Matar','4.03','3');
			insert into canciones values(06,'Lattice','4.54','3');
			insert into canciones values(07,'Visitantes','3.47','5');
			insert into canciones values(08,'Visiones','2.28','3');
			insert into canciones values(09,'Luna LLena','3.43','3');
			insert into canciones values(10,'Birdie','3.36','3');
			insert into canciones values(11,'Rue Vieille Du Temple','3.35','4');
			insert into canciones values(12,'Live in Stereo','3.30','4');
			insert into canciones values(13,'Cero No ser','2.55','3');
	insert into album (5002,'Solstis','2014',5000)
			insert into canciones values(01,'Aurora Boreal','3.38','5');
			insert into canciones values(02,'Brillas','3.46','5');
			insert into canciones values(03,'Carmin','3.51','5');
			insert into canciones values(04,'Souvenir','3.59','5');
			insert into canciones values(05,'Como Tú','3.52','5');
			insert into canciones values(06,'Perdonar','3.38','4');
			insert into canciones values(07,'Ressistolux','3,09','4');
			insert into canciones values(08,'Pérdida Total','3.48','3');
			insert into canciones values(09,'Femme Fatal','4.08','3');
			insert into canciones values(10,'Resguardum Ether','7.25','4');

insert into artista values (6000, 'Jamiroquai', 'Inglaterra, Reino Unido', 234, 955);
  insert into album values (6001,'Automaton',2017, 6000);
      insert into canciones values (1,'Shake It On', '5:14', '★★★');
      insert into canciones values (2, 'Automaton', '4:48', '★★★★');
      insert into canciones values (3, 'Cloud 9', '3:57', '★★★★');
      insert into canciones values (4, 'Superfresh', '3:48', '★★★');
      insert into canciones values (5, 'Hot Property', '4:32','★★★★★');
      insert into canciones values (6, 'Something About You', '3:59', '★★★');
      insert into canciones values (7, 'Summer Girl', '5:32', '★★★★');

insert into artista values (7000, 'Los Ángeles Azules', 'Ciudad de México ,México', 456, 872);
  insert into album values (7001, 'De Plaza en Plaza', 2016, 7000);
    insert into canciones values (1, 'La Cumbia del Infinito', '3:22','★★');
    insert into canciones values (2, 'Ay Amor', '3:45', '★★★★');
    insert into canciones values (3, 'Mi Niña Mujer', '3:14', '★★★★★');
    insert into canciones values (4, 'Mi Cantar', '4:13', '★★★');
    insert into canciones values (5, 'Por Tu Amor', '3:22', '★★★★★');
    insert into canciones values (6, 'Las Maravillas de la Vida', '★★★');
    insert into canciones values (7, 'Amigos Nada Más', '3:32', '★★★★★');
    insert into canciones values (8, 'Me Haces Falta Tú', '3:24', '★★★★');
    insert into canciones values (9, 'La Cadenita', '2:39', '★★★★★');
    insert into canciones values (10, 'Cumbia del Acordeón', '4:42', '★★★★★');
    insert into cancones values (11, 'Hermoso Bebé', '3:23', '★★★★');
  insert into album values (7002, 'Viernes Cultural', 2015, 7000);
    insert into canciones values (1, 'Viernes Cultural', '4:11', '★★★');
    insert into canciones values (2, 'La Cadenita', '2:38', '★★★★');
    insert into canciones values (3, 'Paso la Vida Pensando', '4:56', '★★★');
    insert into canciones values (4, 'Toma Que Toma', '2:37', '★★★★');
    insert into canciones values (5, 'Amigos Nada Más', '3:33', '★★★');
    insert into canciones values (6, '20 Rosas', '3:15', '★★★');
    insert into canciones values (7, 'Cumbia Popular', '3:19', '★★★★');
    insert into canciones values (8, 'Kumbia en la playa', '5:26', '★★★');

insert into artista (8000, 'Los Caligaris', 'Córdoba, Argentina', 789, 726);
  insert into album values (8001, 'Somos Todos Vivos', 2016, 8000);
    insert into canciones values (1, 'Todos Locos', '2:31', '★★★');
    insert into canciones values (2, 'Mi Estanciera y Yo', '★★★');
    insert into canciones values (3, 'Aunque no quiero', '3:33', '★★★');
    insert into canciones values (4, 'Que corran', '5:17', '★★★★');
    insert into canciones values (5, 'Mejilla Izquierda', '3:23', '★★★★');
    insert into canciones values (6, 'Añejo W', '4:23', '★★★');
    insert into canciones values (7, 'Luchamos por la Causa', '3:38', '★★★');
  insert into album values (8002, 'Bailarín Apocalíptico', 2011, 8000);
    insert into canciones values (1, 'Bailarín Apocalítico', '3:46', '★★★');
    insert into canciones values (2, 'Razón', '3:16', '★★★★★');
    insert into canciones values (3, 'El Secreto', '3:28', '★★★★');
    insert into canciones values (4, 'Vereda', '4:11', '★★★');
    insert into canciones values (5, 'Pecado de Juventud', '3:02');
    insert into canciones values (6, 'Rimas Perfectas', '3:12', '★★');
    insert into canciones values (7, 'Infierno', '3:21', '★★★★');
    insert into canciones values (8, 'Purgatorio', '1:31', '★★★');
    insert into canciones values (9, 'Tras las Sierras', '4:32', '★★★★');
    insert into canciones values (10, 'Cicatriz', '3:29', '★★');
    insert into canciones values (11, 'Entre Vos y Yo', '4:38', '★★★★★');

insert into artista values (9000, 'Los Amigos Invisibles', 'Caracas, Venezuela', 112, 423);
  insert into album values (9001, 'El Paradise', 2016, 9000);
    insert into canciones values (1, 'Llegando', '0:23', ' ');

insert into artista (15000, 'Alberto Barros', 'Cali, Colombia', 587, 233);
